### ISSUE TITLE
FileNotFoundError: [Errno 2] File b'output/valid-features-obj/metadata.csv' does not exist: b'output/valid-features-obj/metadata.csv'

### ISSUE THREAD

**Issue by nakulp21** [krasserm/fairseq-image-captioning#22]
While training the model I'm getting this error. The directory "valid-features-obj" is itself not created. I'm using an AMD64 gpu instead of NVIDIA. 
```
Traceback (most recent call last):
  File "/home/nakul/anaconda3/envs/fairseq-image-captioning/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/nakul/anaconda3/envs/fairseq-image-captioning/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/nakul/anaconda3/envs/fairseq-image-captioning/lib/python3.6/site-packages/fairseq_cli/train.py", line 337, in <module>
    cli_main()
  File "/home/nakul/anaconda3/envs/fairseq-image-captioning/lib/python3.6/site-packages/fairseq_cli/train.py", line 333, in cli_main
    main(args)
  File "/home/nakul/anaconda3/envs/fairseq-image-captioning/lib/python3.6/site-packages/fairseq_cli/train.py", line 48, in main
    task.load_dataset(valid_sub_split, combine=False, epoch=0)
  File "/home/nakul/Pycharm/Pycharm Projects/Project/task.py", line 62, in load_dataset
    image_metadata = data.read_image_metadata(image_metadata_file)
  File "/home/nakul/Pycharm/Pycharm Projects/Project/data.py", line 39, in read_image_metadata
    df = pd.read_csv(file)
  File "/home/nakul/anaconda3/envs/fairseq-image-captioning/lib/python3.6/site-packages/pandas/io/parsers.py", line 685, in parser_f
    return _read(filepath_or_buffer, kwds)
  File "/home/nakul/anaconda3/envs/fairseq-image-captioning/lib/python3.6/site-packages/pandas/io/parsers.py", line 457, in _read
    parser = TextFileReader(fp_or_buf, **kwds)
  File "/home/nakul/anaconda3/envs/fairseq-image-captioning/lib/python3.6/site-packages/pandas/io/parsers.py", line 895, in __init__
    self._make_engine(self.engine)
  File "/home/nakul/anaconda3/envs/fairseq-image-captioning/lib/python3.6/site-packages/pandas/io/parsers.py", line 1135, in _make_engine
    self._engine = CParserWrapper(self.f, **self.options)
  File "/home/nakul/anaconda3/envs/fairseq-image-captioning/lib/python3.6/site-packages/pandas/io/parsers.py", line 1917, in __init__
    self._reader = parsers.TextReader(src, **kwds)
  File "pandas/_libs/parsers.pyx", line 382, in pandas._libs.parsers.TextReader.__cinit__
  File "pandas/_libs/parsers.pyx", line 689, in pandas._libs.parsers.TextReader._setup_parser_source
FileNotFoundError: [Errno 2] File b'output/valid-features-obj/metadata.csv' does not exist: b'output/valid-features-obj/metadata.csv'
```

**Comment by krasserm** [comment]
Looks like you didn't [pre-prcess object features](https://github.com/krasserm/fairseq-image-captioning/blob/master/README.md#pre-process-object-features).
